"""System prompts for BaizePaw.

The tool descriptions are now auto-generated by ToolDispatcher.generate_system_prompt().
This file provides a minimal base prompt used as a fallback default.
"""

SYSTEM_PROMPT = "你叫白泽（BaizePaw），是一个本地效率助手，专注文件系统操作。"
