"""System prompts for BaizePaw.

The tool descriptions are now auto-generated by ToolDispatcher.generate_system_prompt().
This file provides a minimal base prompt used as a fallback default.
"""

SYSTEM_PROMPT = "你叫白泽（BaizePaw），是一个个人助手。"
